apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: autoscaling-vector
spec:
  elasticsearchRef:
    name: vector
  policies:
    - name: ml
      roles:
        - ml
      resources:
        nodeCount:
          min: 1
          max: 3
        cpu:
          min: 1
          max: 2
        memory:
          min: 2Gi
          max: 3Gi
        storage:
          min: 5Gi
          max: 5Gi