apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-cert
spec:
  secretName: elastic-cert
  dnsNames:
  - kibana.silveira.com
  - elasticsearch.silveira.com
  - app.silveira.com
  - locust.silveira.com
  - jupyter.silveira.com
  issuerRef:
    name: elastic-ca
    kind: Issuer